"""updating user table

Revision ID: 5caca0bf2b32
Revises: e20acb2ff5be
Create Date: 2020-09-14 13:02:04.058357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5caca0bf2b32'
down_revision = 'e20acb2ff5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('gender')
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_dob', table_name='user')
    op.drop_index('ix_user_fist_name', table_name='user')
    op.drop_index('ix_user_gender', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    op.drop_column('user', 'fist_name')
    op.drop_column('user', 'username')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'dob')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=6), nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('fist_name', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=1)
    op.create_index('ix_user_gender', 'user', ['gender'], unique=1)
    op.create_index('ix_user_fist_name', 'user', ['fist_name'], unique=1)
    op.create_index('ix_user_dob', 'user', ['dob'], unique=False)
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
