"""updated user table

Revision ID: ac1de5f3f3a6
Revises: 8a7588a32f86
Create Date: 2020-09-13 14:13:17.581261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1de5f3f3a6'
down_revision = '8a7588a32f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('fist_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=6), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_dob'), 'user', ['dob'], unique=False)
    op.create_index(op.f('ix_user_fist_name'), 'user', ['fist_name'], unique=True)
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=True)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_index(op.f('ix_user_fist_name'), table_name='user')
    op.drop_index(op.f('ix_user_dob'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'fist_name')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
