"""users table

Revision ID: d7319f50100d
Revises: 5caca0bf2b32
Create Date: 2020-09-25 15:18:36.748069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7319f50100d'
down_revision = '5caca0bf2b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('image_loc', sa.String(length=150), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('strain', sa.String(length=100), nullable=True),
    sa.Column('thc_content', sa.String(length=5), nullable=True),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('harvested', sa.DateTime(), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('on_sale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_added'), 'product', ['added'], unique=False)
    op.create_index(op.f('ix_product_harvested'), 'product', ['harvested'], unique=False)
    op.create_index(op.f('ix_product_on_sale'), 'product', ['on_sale'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_on_sale'), table_name='product')
    op.drop_index(op.f('ix_product_harvested'), table_name='product')
    op.drop_index(op.f('ix_product_added'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
